services:
  db:
    container_name: vamoscozinhar-db
    image: postgres:17.6-alpine3.22
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  mem_db:
    container_name: vamoscozinhar-mem-db
    image: valkey/valkey:8.1.3-alpine3.22
    ports:
      - "6379:6379"